#!/usr/bin/env php
<?php

if (!defined('PIONIA_START')) {
    define('PIONIA_START', microtime(true));
}

$code = (require __DIR__ .'/bootstrap/application.php')
        ->bootConsole();

exit($code);
